In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sb

f = pd.read_csv("./data/winemag-data-130k-v2.csv")

f.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

# Eploring the dataset

In [2]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

In [3]:
f.describe()

          Unnamed: 0         points          price
count  129971.000000  129971.000000  120975.000000
mean    64985.000000      88.447138      35.363389
std     37519.540256       3.039730      41.022218
min         0.000000      80.000000       4.000000
25%     32492.500000      86.000000      17.000000
50%     64985.000000      88.000000      25.000000
75%     97477.500000      91.000000      42.000000
max    129970.000000     100.000000    3300.000000

In [5]:
f.shape

(129971, 14)

In [12]:
f.isnull().sum()

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [14]:
f.nunique()

Unnamed: 0               129971
country                      43
description              119955
designation               37979
points                       21
price                       390
province                    425
region_1                   1229
region_2                     17
taster_name                  19
taster_twitter_handle        15
title                    118840
variety                     707
winery                    16757
dtype: int64

In [15]:
f.country.value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Macedonia                    12
Czech Republic               12
Serbia                       12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [24]:
f_clean = f.dropna(subset=["price", "points"]).copy()

# Analyze data

In [28]:
country_stats = (
    f.groupby("country")
    .agg(avg_price=("price", "mean"), avg_points=("points", "mean"), nr_reviews=("country", "size"))
)

reliable = country_stats[country_stats.nr_reviews > 15]

reliable.sort_values("avg_points", ascending=False)

              avg_price  avg_points  nr_reviews
country
England       51.681159   91.581081          74
Austria       30.762772   90.101345        3345
Germany       42.257547   89.851732        2165
Canada        35.712598   89.369650         257
Hungary       40.648276   89.191781         146
France        41.139120   88.845109       22093
Australia     35.437663   88.580507        2329
Morocco       19.500000   88.571429          28
US            36.573464   88.563720       54504
Italy         39.663770   88.562231       19540
Israel        31.768916   88.471287         505
New Zealand   26.931785   88.303030        1419
Portugal      26.218256   88.250220        5691
Turkey        24.633333   88.088889          90
Slovenia      24.812500   88.068966          87
South Africa  24.668987   88.056388        1401
Bulgaria      14.645390   87.936170         141
Georgia       19.321429   87.686047          86
Lebanon       30.685714   87.685714          35
Spain         28.215275   87.288337        6645
Greece        22.364425   87.283262         466
Croatia       25.450704   87.219178          73
Moldova       16.745763   87.203390          59
Uruguay       26.403670   86.752294         109
Argentina     24.510117   86.710263        3800
Chile         20.786458   86.493515        4472
Romania       15.241667   86.400000         120
Mexico        26.785714   85.257143          70
Brazil        23.765957   84.673077          52
Peru          18.062500   83.562500          16

In [ ]:
sb.scatterplot(data=country_stats, x="nr_reviews", y="avg_points")
plt.xscale("log")  # log scale because some have lots of reviews while other have less
plt.xlabel("Number of reviews (log scale)")
plt.ylabel("Average points")
plt.show()